version: '3'

services:
  backend:
    build: ./backend/
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    command: air

  frontend:
    build: ./frontend
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    ports:
      - 88:8888
    volumes:
      - ./frontend:/app
    command: npm run serve
