version: '3'

services:
  backend:
    build: ./backend/
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app
    command: air
  frontend:
    build: ./frontend
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    ports:
      - 88:8888
    volumes:
      - /app/node_modules
      - ./frontend:/app
    command: npm run serve
  db:
    build: ./db
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=golang_pass
      - POSTGRES_USER=golang_usr
      - POSTGRES_DB=golang_db
